Feature/137 update template
Eastern-Research-Group/mywaterway pull request #607
Opened 2022-04-26 18:58 UTC by maxdiebold-erg

## Related Issues:
* HMW-137

## Main Changes:
* Updated the HTML templates to match those on the main [https://www.epa.gov]() site.
* The EPA navigation links above the HMW content are now drop-down menus.

## Steps To Test:
1. Go to [http://localhost:3000/](), and browse any site under the `mywaterway` subdomain
2. Decrease the screen width to confirm responsiveness on mobile browsers
3. Disable JavaScript to confirm that the interface adapts and the proper alerts are presented to the user

## TODO:
- [ ] I included the "return to top" button from [https://www.epa.gov](), but it might get in the way of the HMW application, so it could use some usability testing.

2022-04-26 18:58 UTC, maxdiebold-erg commented
@cschwinderg

2022-05-02 17:07 UTC, maxdiebold-erg commented
@cschwinderg yeah it broke a lot more than I thought, I'll work on that now.

2022-05-04 14:43 UTC, cschwinderg requested changes
@maxdiebold-erg I'm not sure if this is complete yet, but I figured I would take a look while I was fixing the merge conflicts. 

This looks good! Thanks for working on this.

Can you fix the minor code smell that sonar cloud flagged? The comments below are related to that code smell.

2022-05-04 14:43 UTC, cschwinderg commented on app/client/public/index.html
> +      }
```suggestion
```

Related to the comment above, this one should be deleted.

2022-05-04 15:12 UTC, maxdiebold-erg commented
Yes, I'll take care of that. I'm not positive it's complete either, but as far as I can see things fit!

2023-12-29 17:38 UTC, closed without merging