HMW-200 …
Eastern-Research-Group/mywaterway pull request #639
Opened 2022-05-25 13:37 UTC by cschwinderg

## Related Issues:
* https://jira.epa.gov/browse/HMW-200

## Main Changes:
* Removed the Temp Monitoring Clustering switch and updated the code so that clustering is automatically activated if there are more than 20 stations in the HUC.

## Steps To Test:
1. Navigate to http://localhost:3000/community/portland%20or/monitoring
2. Verify the Past Water Conditions layer is being clustered
3. Verify the `TEMP Monitoring Clustering` switch is no longer in the app
4. Navigate to http://localhost:3000/community/columbia%20sc/monitoring
5. Verify the Past Water Conditions layer is not being clustered
6. Verify the `TEMP Monitoring Clustering` switch is no longer in the app

2022-05-25 16:46 UTC, maxdiebold-erg requested changes
@cschwinderg The clustering looks good, I think you picked a good radius so the clusters don't overlap. However, the highlighting isn't working for me when hovering over an accordion item.

I suspect this is because the clusters are different graphics. What you would need to do, I think, is query the visible graphics with `FeatureLayerView.queryFeatures()` to get the cluster graphics, then get the underlying features associated with each graphic, by setting the graphic's ID in the layerView query's aggregateIds property and querying each graphic.

Or, there might be a way to query the visible graphics by an underlying feature ID, but I can't seem to find where the feature data is stored in the FeatureReductionCluster object.

2022-05-25 16:57 UTC, cschwinderg commented on app/client/src/components/shared/LocationMap.js
> +        popupTemplate: {
Those action buttons are the default buttons for cluster popups. I don't see any built in ways to default the popup to the list in the ArcGIS JS API. We could do something hacky where we click the button through code, but I think it is better to just stick with default behavior of the popup.

2022-05-25 17:00 UTC, cschwinderg commented
@maxdiebold-erg Thanks for noticing the highlighting issue. I think I'll create a separate ticket/PR for that, since that could end up being a complicated issue. I'll leave this PR as just being about making clustering enabled when a HUC has more than 20 stations.

2022-05-25 18:02 UTC, cschwinderg commented
@maxdiebold-erg I don't define that. Those items are in there by default in the ArcGIS JS API and the API doesn't provide an easy way to default to that list view.

2022-05-26 14:07 UTC, cschwinderg commented
@maxdiebold-erg I've been researching the highlighting issue. Unfortunately, the `FeatureLayerView.queryFeatures()` doesn't return the cluster graphics. I haven't been able to find any other way to query the clusters or even figure out if the graphic is in a cluster. 

The API only seems to allow you to find out what features are in a cluster if you click on a cluster. I'm going to post a question on the Esri forums about this. 

I'm going to go ahead and merge this PR in though, since the highlighting and possible map popup changes will be separate tickets/PRs.

2022-05-26 14:07 UTC, merged