Feature/11 location page updates
Eastern-Research-Group/mywaterway pull request #702
Opened 2022-08-08 13:30 UTC by maxdiebold-erg

## Related Issues:
* [HMW-11](https://jira.epa.gov/secure/RapidBoard.jspa?rapidView=864&view=detail&selectedIssue=HMW-11)

## Main Changes:
* Changed occurrences of 'station' to 'location'.
* Re-combined the added the org ID back to the site ID.
* Added a help tooltip to describe the site ID.
* Updated the download link to use only characteristic names and to use a POST request, while the WQP link uses only characteristic types.
* Updated the date slider to only show the year if the start and end dates are the same.
* Added some Cypress tests.

## Steps To Test:
1. Go to a monitoring location page, e.g. [http://localhost:3000/location/STORET/CBP_WQX/CBP_WQX-01651770/](http://localhost:3000/location/STORET/CBP_WQX/CBP_WQX-01651770/)
2. Select a characteristic from the upper-right table that only has one year of data, such as _Orthoposphate_
3. Confirm that only the year is shown where the date slider would be
4. Select the characteristic _Height, gage_
5. Confirm that on days with multiple measurements, both are shown on the graph and in the hover tooltip
6. In the download section, deselect a type, then select a single characteristic from that type
7. Confirm that the download link returns the correct number of results

2022-08-09 20:02 UTC, cschwinderg requested changes
Looks good!

I found some minor issues and some accessibility issues (listed below).

2022-08-10 13:53 UTC, maxdiebold-erg commented on app/client/src/components/shared/HelpTooltip.js
> +        data-testid="tooltip-trigger"
Okay that's handy, that's a Bootstrap convention?

2022-08-10 13:55 UTC, maxdiebold-erg commented on app/client/src/components/pages/MonitoringLocation.js
> +              aria-label={charc.name}
Good to know, the aria-label was just for Cypress, so I appreciate the accessibility suggestions!

2022-08-10 15:27 UTC, cschwinderg requested changes
Thank you for making those changes. I just have one more small change below.

2022-08-10 15:27 UTC, cschwinderg commented on app/client/src/components/shared/HelpTooltip.js
> +        <span className="sr-only">Information Tooltip</span>
Can you remove the usage of `data-testid` on line 79 above, since it is no longer used anywhere?

2022-08-10 15:28 UTC, cschwinderg commented on app/client/src/components/shared/HelpTooltip.js
> +        <span className="sr-only">Information Tooltip</span>
I'll go ahead and commit this change up and merge this in, so you can disregard this.

2022-08-10 15:30 UTC, cschwinderg approved these changes

2022-08-10 15:31 UTC, merged