Feature/typescript migration 2
Eastern-Research-Group/mywaterway pull request #734
Opened 2022-09-08 19:26 UTC by maxdiebold-erg

## Main Changes:
* Continuing the conversion of the codebase to TypeScript.

2022-09-15 19:25 UTC, cschwinderg commented
@maxdiebold-erg Just starting to look at this. When you get a chance, can you fix the merge conflicts.

2022-09-15 21:06 UTC, maxdiebold-erg commented
@cschwinderg The merge conflicts should be fixed now. In the process, I found a DOM nesting issue with the tooltips, so I altered that a bit on the Monitoring Report page, too.

2022-09-16 15:10 UTC, cschwinderg requested changes
Thank you for working on this. Looks great! Glad to see us moving more towards TypeScript. 

I did find a bug and some other small items (listed below).

2022-09-16 15:46 UTC, maxdiebold-erg commented on app/client/src/types/index.ts
> +        noDataValue: -999999;
True, don't know why I made that assumption.

2022-09-16 15:47 UTC, maxdiebold-erg commented on app/client/src/utils/mapFunctions.tsx
> +  });
Good catch!

2022-09-16 16:53 UTC, maxdiebold-erg commented on app/client/src/components/shared/MapWidgets.tsx
> +      if (isTileLayer(layer) || isMapImageLayer(layer)) {
True! I went ahead and made a union type for all Layer subclasses with sublayers.

2022-09-16 16:55 UTC, maxdiebold-erg commented
@cschwinderg Good calls, I made the changes you pointed out, let me know if you see any others.

2022-09-16 17:38 UTC, cschwinderg approved these changes
Looks good, thanks for making those changes.

2022-09-16 17:38 UTC, merged