Feature/315 surrounding monitoring stations layer
Eastern-Research-Group/mywaterway pull request #751
Opened 2022-10-11 19:33 UTC by cschwinderg

## Related Issues:
* https://jira.epa.gov/browse/HMW-315

## Main Changes:
* Added a surrounding past water conditions widget.
  * I went ahead and added this to the community, tribal, and water body report pages. We can show EPA and remove it from those other pages if necessary.

## Steps To Test:
1. Navigate to http://localhost:3000/community/dc/overview
2. Turn on the surrounding past water conditions widget
3. Verify it works
4. Navigate to http://localhost:3000/waterbody-report/DOEE/DCANA00E_01/2020
5. Repeat steps 2 and 3.
6. Navigate to http://localhost:3000/tribe/DELAWARENATION
7. Repeat steps 2 and 3.

2022-10-12 13:12 UTC, maxdiebold-erg requested changes
Looking good! I added a couple notes just about variable names and a comment.

Also, do we want the cluster settings to reset on change of location, like the other Past Water Conditions layer does? If so, we could add it to the same effect:
```
// restores cluster settings on change of location
  useEffect(() => {
    if (surroundingMonitoringLocationsLayer && !surroundingMonitoringLocationsLayer.featureReduction) {
      surroundingMonitoringLocationsLayer.featureReduction = monitoringClusterSettings;
    }
    if (!locationCount || locationCount <= 20) return;
    if (!monitoringLocationsLayer || monitoringLocationsLayer.featureReduction)
      return;
    monitoringLocationsLayer.featureReduction = monitoringClusterSettings;
  }, [locationCount, monitoringLocationsLayer, surroundingMonitoringLocationsLayer]);
```

I agree that we should see what EPA thinks about putting the widget on the other pages. If we leave it on the Monitoring tab, we should probably indicate to users that the date slider doesn't affect the surrounding monitoring locations.

2022-10-12 13:12 UTC, maxdiebold-erg commented on app/client/src/components/shared/MapWidgets.tsx
> +        const southwestWM = new Point({
This is just a variable name, but it could be confusing in the future:
```suggestion
        const southeastWM = new Point({
```

2022-10-12 13:12 UTC, maxdiebold-erg commented on app/client/src/components/shared/MapWidgets.tsx
> +          southwestWM,
Similar to above:
```suggestion
        const southeast = webMercatorUtils.webMercatorToGeographic(
          southeastWM,
```

2022-10-12 13:12 UTC, maxdiebold-erg commented on app/client/src/components/shared/MapWidgets.tsx
> +        const east = southwest.longitude;
Similar to above:
```suggestion
        const south = southeast.latitude;
        const east = southeast.longitude;
```

2022-10-12 13:12 UTC, maxdiebold-erg commented on app/client/src/components/shared/MapWidgets.tsx
> +    // zoomed out to much
Just a small comment typo:
```suggestion
    // zoomed out too much
```

2022-10-13 12:01 UTC, cschwinderg commented
@maxdiebold-erg Good catch! Should be good to go now.

2022-10-13 12:44 UTC, maxdiebold-erg approved these changes
Great!

2022-10-13 12:44 UTC, merged