Bugfix/545 detailed uses issues
Eastern-Research-Group/mywaterway pull request #871
Opened 2023-07-20 20:31 UTC by cschwinderg

## Related Issues:
* [HMW-545](https://jira.epa.gov/browse/HMW-545)

## Main Changes:
* Fixed issue of glossary being re-opened when closing the detailed uses modal.
  * Note: This was caused by radix-ui. Radix-ui uses the `aria-hidden` package, which when called removes the `aria-hidden` attribute from the glossary panel, instead of setting it to true. 

## Steps To Test:
1. Navigate to http://localhost:3000/community/blacksburg,%20va/overview
2. Open one of the waterbodies
3. Click on one of the glossary items
4. Click on one of the detailed use buttons (i.e., info icons)
5. Verify the glossary is closed and the modal is opened
6. Close the modal
7. Verify the glossary does not open back up
    * Note: If you repeat the above steps on the dev site, the glossary will be visible and show all terms.
8. Verify other usages of the glossary still works correctly

2023-07-21 13:59 UTC, maxdiebold-erg requested changes
Nice catch, and clean fix!

While reviewing this, I saw a couple accessibility issues being reported. These are related to using an icon as a trigger (shouldn't apply `aria-expanded` to `i` elements and improper semantics for a clickable element). I think we should wrap these in unstyled buttons, like we do with the tooltip triggers. I tested this with the following patch:
```
diff --git a/app/client/src/components/shared/HelpTooltip.tsx b/app/client/src/components/shared/HelpTooltip.tsx
index f38b4f33..8d8e1b54 100644
--- a/app/client/src/components/shared/HelpTooltip.tsx
+++ b/app/client/src/components/shared/HelpTooltip.tsx
@@ -3,7 +3,7 @@ import { TooltipPopup, useTooltip } from '@reach/tooltip';
 import { css } from 'styled-components/macro';
 // styles
 import '@reach/tooltip/styles.css';
-import { colors } from 'styles';
+import { colors, iconButtonStyles } from 'styles';
 // types
 import type { Position } from '@reach/tooltip';
 import type { ReactElement, ReactNode, Ref } from 'react';
@@ -11,18 +11,13 @@ import type { ReactElement, ReactNode, Ref } from 'react';
 /*
 ## Styles
 */
-const helpIconStyles = css`
-  cursor: help;
+const modifiedIconButtonStyles = css`
+  ${iconButtonStyles}
+  cursor: unset !important;
 `;
 
-const tooltipIconStyles = css`
-  background: none;
-  border: none;
-  color: inherit;
-  cursor: unset !important;
-  margin: 0;
-  outline: inherit;
-  padding: 0;
+const helpIconStyles = css`
+  cursor: help;
 `;
 
 const tooltipStyles = css`
@@ -94,7 +89,7 @@ function HelpTooltip({
   return (
     <Tooltip label={label} triggerRef={triggerRef}>
       <button
-        css={tooltipIconStyles}
+        css={modifiedIconButtonStyles}
         onClick={(_ev) => triggerRef.current?.focus()}
         ref={triggerRef}
       >
diff --git a/app/client/src/components/shared/Modal.tsx b/app/client/src/components/shared/Modal.tsx
index 8ad2dc76..0ab3474d 100644
--- a/app/client/src/components/shared/Modal.tsx
+++ b/app/client/src/components/shared/Modal.tsx
@@ -4,7 +4,7 @@ import * as Dialog from '@radix-ui/react-dialog';
 // types
 import type { ReactNode } from 'react';
 // styles
-import { colors } from 'styles/index.js';
+import { colors, iconButtonStyles } from 'styles/index.js';
 
 const buttonContainerStyles = css`
   margin-top: 15px;
@@ -225,7 +225,13 @@ export function DisclaimerModal({
       label="Disclaimer"
       triggerElm={
         infoIcon ? (
-          <i css={helpIconStyles} className="fas fa-question-circle"></i>
+          <button aria-label="Disclaimer" css={iconButtonStyles}>
+            <i
+              aria-hidden
+              css={helpIconStyles}
+              className="fas fa-question-circle"
+            ></i>
+          </button>
         ) : (
           <button
             css={disclaimerButtonStyles}
diff --git a/app/client/src/components/shared/WaterbodyInfo.tsx b/app/client/src/components/shared/WaterbodyInfo.tsx
index c93e1672..f4cb373b 100644
--- a/app/client/src/components/shared/WaterbodyInfo.tsx
+++ b/app/client/src/components/shared/WaterbodyInfo.tsx
@@ -60,6 +60,7 @@ import {
   disclaimerStyles,
   fonts,
   iconStyles,
+  iconButtonStyles,
   modifiedTableStyles,
   tableStyles,
 } from 'styles/index.js';
@@ -135,11 +136,6 @@ function labelValue(
 /*
 ## Styles
 */
-const detailedUsesIconStyles = css`
-  margin-right: 0.25rem;
-  color: #485566;
-`;
-
 const linkSectionStyles = css`
   p {
     padding-bottom: 1.5em;
@@ -150,6 +146,12 @@ const linkSectionStyles = css`
   }
 `;
 
+const modifiedIconButtonStyles = css`
+  ${iconButtonStyles}
+  margin-right: 0.25rem;
+  color: #485566;
+`;
+
 const popupContainerStyles = css`
   margin: 0;
   overflow-y: auto;
@@ -629,15 +631,19 @@ function WaterbodyInfo({
                             maxWidth="35rem"
                             onClose={() => setSelectedUseField(null)}
                             triggerElm={
-                              <i
-                                className="fas fa-info-circle"
-                                css={detailedUsesIconStyles}
-                                title={`View detailed uses for ${useField.label}`}
-                                onClick={() => {
-                                  setSelectedUseField(useField);
-                                  fetchDetailedUses();
-                                }}
-                              ></i>
+                              <button
+                                aria-label={`View detailed uses for ${useField.label}`}
+                                css={modifiedIconButtonStyles}
+                              >
+                                <i
+                                  aria-hidden
+                                  className="fas fa-info-circle"
+                                  onClick={() => {
+                                    setSelectedUseField(useField);
+                                    fetchDetailedUses();
+                                  }}
+                                ></i>
+                              </button>
                             }
                           >
                             {useAttainments.status === 'fetching' && (
@@ -646,10 +652,7 @@ function WaterbodyInfo({
 
                             {selectedUseField &&
                               useAttainments.status === 'success' && (
-                                <table
-                                  css={modalTableStyles}
-                                  className="table"
-                                >
+                                <table css={modalTableStyles} className="table">
                                   <thead>
                                     <tr>
                                       <th>
diff --git a/app/client/src/styles/index.js b/app/client/src/styles/index.js
index 67fd1082..83e811a4 100644
--- a/app/client/src/styles/index.js
+++ b/app/client/src/styles/index.js
@@ -59,6 +59,15 @@ const iconStyles = css`
   margin-right: 5px;
 `;
 
+const iconButtonStyles = css`
+  background: none;
+  border: none;
+  color: inherit;
+  margin: 0;
+  outline: inherit;
+  padding: 0;
+`;
+
 const fonts = {
   primary: `'Source Sans Pro', 'Helvetica Neue', 'Helvetica', 'Roboto', 'Arial', sans-serif`,
   secondary: `'Roboto Slab', serif`,
@@ -144,6 +153,7 @@ export {
   downloadLinksStyles,
   fonts,
   iconStyles,
+  iconButtonStyles,
   modifiedTableStyles,
   reactSelectStyles,
   tableStyles,
```

2023-07-24 15:13 UTC, cschwinderg commented
Good catch! I implemented the suggested changes.

2023-07-24 20:52 UTC, maxdiebold-erg approved these changes

2023-07-24 20:53 UTC, maxdiebold-erg commented
Thanks for making that change!

2023-07-24 20:53 UTC, merged