Feature/555 add cyan to overview
Eastern-Research-Group/mywaterway pull request #872
Opened 2023-07-21 21:55 UTC by maxdiebold-erg

## Related Issues:
* [HMW-555](https://jira.epa.gov/browse/HMW-555)

## Main Changes:
* Added CyAN content to the Community page's _Overview_ tab.
* Added a `ResizeObserver` to the `VirtualizedList` component to address rows with dynamically-sized content.
  * This addition caused many errors with the message "ResizeObserver loop completed with undelivered notifications" or "ResizeObserver loop limit exceeded", which have not been thrown with other instances of `ResizeObserver` in the app. This is due to the speed with which elements in the virtualized list are added to the observation list: the errors are triggered when `ResizeObserver` fears an infinite loop, which is not the case here. As stated by the author (https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded#comment86691361_49384120 and https://github.com/WICG/resize-observer/issues/38), this error is usually benign and can be ignored.
* Fixed some style issues in the popups.
* Changed the text 'CyAN Satellite Imagery' to 'Harmful Algal Blooms (HABs)'.

## Steps To Test:
1. Navigate to http://localhost:3000/community/lake%20okeechobee/overview.
2. Open the _Water Monitoring Locations_ tab, and confirm that the CyAN layer toggles on (and is visible), along with the other monitoring layers.
3. Expand the Lake Okeechobee CyAN list item, and confirm that all content is visible without scrolling in the accordion item.
4. Confirm the proper text changes were made in this tab and in the "Current Water Conditions" of the _Water Monitoring_ tab.

## TODO:
- [ ] We should wait to hear back about the proper text changes before merging this in. While the email states the change should be "Harmful Algal Blooms (HABs)", "Potentially Harmful Algal Blooms (HABs)" was discussed in a recent meeting, along with other potential changes.

2023-07-24 20:42 UTC, cschwinderg requested changes
I'm seeing some rendering issues with the `ResizeObserver`. On smaller screens (1000px X 720px) a scrollbar is shown for the accordion headers. Also, I'm seeing a lot of flickering (gif below) on smaller screens (1000px X 720px). It seems like removing `, overflowX: 'hidden'` from line 120 of `VirtualizedList.tsx` fixes the issue.

What was the issue the `ResizeObserver` is intended to fix? I'm assuming it is just to move away from reach-ui.

![renderingIssue](https://github.com/Eastern-Research-Group/mywaterway/assets/46329268/3b010340-5651-4005-bda1-8e227f038df3)

An unrelated issue, the `pageYOffset` (used on line 89 of the `VirtualizedList.tsx` file) value has been deprecated. We should switch to `scrollY`.

2023-07-24 21:26 UTC, maxdiebold-erg commented
The `ResizeObserver` is for properly resizing when asynchronous content is loaded inside the virtualized list (i.e. the CyAN content). Otherwise, the expanded list items will have the height that is calculated when loading spinners are visible. 

It looks like `react-window` was working on similar functionality with the `DynamicSizeList` (https://github.com/bvaughn/react-window/issues/516) class, but ran into issues. Other similar packages (e.g. [React Virtuoso](https://virtuoso.dev/)) use `ResizeObserver` under the hood.

Good catch on that overflow issue, I'll make those changes.

2023-07-24 21:49 UTC, maxdiebold-erg commented on app/client/src/components/shared/MessageBoxes.js
> +  padding-right: 0.75em !important;
Hmm I thought I was running into specificity issues with the one-liner, but I guess not, I'll make that switch.

2023-07-25 12:03 UTC, cschwinderg approved these changes
Thank you for making those changes. The switch to using `ResizeObserver` makes sense. 

I'm going to go ahead and merge this in. Kiki can let us know what she thinks of the new HABs text during our next meeting.

2023-07-25 12:03 UTC, closed without merging