Feature/137 update epa template
Eastern-Research-Group/mywaterway pull request #920
Opened 2023-12-29 19:33 UTC by maxdiebold-erg

## Related Issues:
* [HMW-137](https://jira.epa.gov/browse/HMW-137)

## Main Changes:
* Updated the base HMTL template to the current one stipulated by EPA.
* Addressed styles that were broken by the update.

## Steps To Test:
1. Test as many pages as possible and verify the appearance of all non-template components are the same as before.
2. Ensure the template is updated on the `400.html` and `500.html` pages.

## NOTES:
All of the auxiliary template files are located under `public/epa-template-files` in both the server and client, so that they could be easily copied/synced. The duplicates will be consolidated when building the application, but there could be a better way to make the files reachable by React during development (I considered symlinks, but I don't think they would play well between operating systems).

2024-01-02 18:56 UTC, cschwinderg requested changes
The header and footer looks good.

Here are some differences that I found (left = new and right = production).

* Fonts in tables in popups seem a to large.
![image](https://github.com/Eastern-Research-Group/mywaterway/assets/46329268/c807f9d6-8d6c-4045-9468-3a095faa578a)

* There is some extra padding on the search in menu and search suggestions menu.
![image](https://github.com/Eastern-Research-Group/mywaterway/assets/46329268/2f571b37-8abc-46e6-81e1-6f7e48c4fef2)

2024-01-02 19:37 UTC, maxdiebold-erg commented on app/client/public/site.webmanifest
> +      "src": "/images/android-chrome-192x192.png",
Good catch, missed updating that file when adding that subdirectory.

2024-01-02 21:38 UTC, maxdiebold-erg commented
I just realized the new template changed the `html` tag's font size, so any `rem`-sized styles will be a bit off. It was previously set at 106.25%, i.e. `17px`, now it is at the default `16px`. I'm not sure if we want to account for this or roll with the new size. The disclaimer modal font seems a bit small.

2024-01-03 13:21 UTC, cschwinderg approved these changes
Looks good! Thanks for making those changes.

2024-01-03 13:21 UTC, merged