feature/672 address codesmells
Eastern-Research-Group/mywaterway pull request #939
Opened 2024-01-29 18:01 UTC by cschwinderg

## Related Issues:
* [HMW-672](https://jira.epa.gov/browse/HMW-672)

## Main Changes:
* Fixed codesmells flagged by sonarcloud.

## Steps To Test:
1. Navigate here
2. Do this
3. Do that

## TODO:
- [ ] Change this
- [ ] Update that
- [ ] Remove this

2024-01-29 22:15 UTC, maxdiebold-erg requested changes
Looks like you caught a lot of them!

I noticed that you used the `uuid` function to address the list index issues in SonarCloud. This might satisfy SonarCloud, but I think this would actually result in worse behavior performance-wise: the `uuid` is random by design, so this will create a new key on each render. Using an array index is as stable as the base array, which in many cases is set in state and is actually quite stable. Still, using the index is not recommended, so using some property or a deterministic hash of it should be used instead. I doubt it will affect performance in most cases, but it's something to keep in mind.

One simple hash (a Java built-in but taken from https://stackoverflow.com/questions/7616461/generate-a-hash-from-string-in-javascript) could be implemented as:
```
function simpleHash(str) {
  let hash = 0;
  if (str.length === 0) return hash;

  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash |= 0; // Convert to 32bit integer
  }

  return hash;
}
```
The other suggestion on the same SO post looks promising, too. I'll note the occurrences I find below.

2024-01-29 22:15 UTC, maxdiebold-erg commented on app/client/src/components/pages/StateTribal.js
> +                          key={uuid()}
I think the source could just be used here:
```suggestion
                          key={source}
```

2024-01-29 22:15 UTC, maxdiebold-erg commented on app/client/src/components/pages/StateTribal.js
> +                                  <div css={keyMetricStyles} key={uuid()}>
Described above:
```suggestion
                                  <div css={keyMetricStyles} key={simpleHash(metric.label)}>
```

2024-01-29 22:15 UTC, maxdiebold-erg commented on app/client/src/components/shared/LocationSearch.js
> +                    return <strong key={uuid()}>{part}</strong>;
I think this is fine as is, honestly the index would be best here.

2024-01-29 22:15 UTC, maxdiebold-erg commented on app/client/src/components/shared/LocationSearch.js
> +                    return <Fragment key={uuid()}>{part}</Fragment>;
Fine as is, or revert to the index.

2024-01-29 22:15 UTC, maxdiebold-erg commented on app/client/src/components/shared/WaterSystemSummary.js
> +                      <li css={rowStyles} key={uuid()}>
Described above:
```suggestion
                      <li css={rowStyles} key={simpleHash(label)}>
```

2024-01-29 22:15 UTC, maxdiebold-erg commented on app/client/src/components/shared/WaterSystemSummary.js
> +                          <th key={uuid()}>{item}</th>
Described above:
```suggestion
                          <th key={simpleHash(item)}>{item}</th>
```

2024-01-29 22:15 UTC, maxdiebold-erg commented on app/client/src/components/shared/WaterSystemSummary.js
> +                          <td key={uuid()}>{item}</td>
Fine as is, or revert to the index.

2024-01-30 14:00 UTC, cschwinderg commented
Some of them I left using `uuid`. I switched some back to `index` and just marked as a false positive in sonarcloud. 

I ended up not using `simpleHash` and instead just used an attribute (or combination of attributes) from the data being displayed. I feel like `simpleHash` doesn't really gain us much. It won't really enforce uniqueness, because the same string will result in the same hash. The only benefit I see is shorter keys in some instances, but I don't think that is worth the extra logic.

2024-01-30 14:05 UTC, maxdiebold-erg commented
Sounds good. Right, the hash would only be for shorter keys, I used it more as an example as opposed to a random ID.

2024-01-30 14:42 UTC, maxdiebold-erg approved these changes
Thanks for making those changes, I think the other changes look good.

2024-01-30 14:42 UTC, maxdiebold-erg commented on app/client/src/components/shared/AddSaveDataWidget.SearchPanel.tsx
> +import React, {
No issue here, but I tested this out and it looks like it doesn't need to be imported if it's only being used as a namespace for types.

2024-01-30 14:45 UTC, merged