Feature/714 climate tab outline
Eastern-Research-Group/mywaterway pull request #964
Opened 2024-04-29 17:54 UTC by cschwinderg

## Related Issues:
* [HMW-714](https://jira.epa.gov/browse/HMW-714)

## Main Changes:
* Added in a Climate tab, still a work in progress.
  * I wired up all of the layers that we already had.
  * I added in the Wild fires layer and wired it up, (not the historical part). 
  * For the date slider I ended up using the esri slider, because it allows vertical orientation. I thought about switching all date sliders over to esri, but wanted to get your opinion first. The one thing that react-ranger seems to do better, is it allows you drag the right handle past the left one and still have a range that makes sense. Esri just doesn't allow the handles to cross.
  * I plan on moving the initial layer configs to a config file. 

## Steps To Test:
1. Navigate to http://localhost:3000/community/020802011001/extreme-weather
2. Verify that layers load (note: a lot of the layers haven't been wired up)
3. Verify the switches make the layers visible/hidden
4. Verify that toggling layer visibilty from the layer list also toggles the corresponding switch
5. Block one of the services
6. Verify the status text, displays `N/A`
7. Verify the popups work on the wildfire layer

## TODO:
- [ ] Move initial layer configs to a config file on S3.
- [ ] Need to get input from EPA on what layers, if any, they want on by default.
- [ ] Wire up remaining switches/statuses.

2024-05-06 18:52 UTC, maxdiebold-erg requested changes
This looks very good!

I don't have a problem with the thumb handles not crossing over in the slider. I do think the accessibility is currently a bit off: when focused on the thumb handles, the screen reader reads the position, not the associated label.

I reached a state where the "Waterbodies" switch was broken a couple times. The easiest way to reproduce the issue is by navigating to a different location by clicking the map.

![switch-error](https://github.com/Eastern-Research-Group/mywaterway/assets/104089016/88e0bd48-66d8-4c78-8488-0c755f8737d8)

I wasn't able to reproduce the issue below, where the fire symbols were absent, but it was curious to me when I saw it. May have been some problem communicating with the server.

![wildfires](https://github.com/Eastern-Research-Group/mywaterway/assets/104089016/f72b59ad-bd92-44ec-bf59-636a9df13f33)

2024-05-08 12:48 UTC, cschwinderg commented
The accessibility of the esri slider wasn't working well with string labels. I ended up switching all of our sliders over to MaterialUI, which supports vertical sliders. Currently the extreme weather and cyan sliders are the only ones that switche to a vertical layout. We can discuss having all of them switch to the vertical layout, but I think the year sliders work well just removing tick marks.

2024-05-08 15:37 UTC, maxdiebold-erg commented
The switches all work well, and the slider looks good!

I wish it was possible to install just the slider from Material UI, but it looks like a package deal.

2024-05-08 15:37 UTC, maxdiebold-erg approved these changes

2024-05-08 15:40 UTC, merged