Feature/744 remove summarize y
Eastern-Research-Group/mywaterway pull request #972
Opened 2024-06-06 18:38 UTC by cschwinderg

## Related Issues:
* [HMW-744](https://jira.epa.gov/browse/HMW-744)

## Main Changes:
* Removed the `summarize=Y` parameter from calls to the `actions` service. 
  * This was done to improve performance, since Attains is unlikely to resolve this issue any time soon.
  * We also use `summarize=Y` for one of our calls to the `assessments` service and for the `plans` service. In these instances `summarize=Y` actually does improve performance.
  * I made the timeout 2 minutes for `actions` service calls, as some locations (Wisconsin) take about a minute to run (used to take about 5 minutes).
* Fixed an issue where clicking on a waterbody, while on the `Restoration Plans` tab or `Protection Projects` accordion with surrounding waterbodies on, would result in the normal waterbody report. These locations should be showing a popup with a list of plans/actions associated with the waterbody.

## Steps To Test:
1. Open the network tab in chrome dev tools
2. Navigate to http://localhost:3000/waterbody-report/DOEE/DCTFS01R_00/2022
3. Verify the `actions` services return in a timely manner
4. Verify the `Plans to Restore Water Quality` section loads with the `Impairments` column filled out
5. Navigate to http://localhost:3000/community/dc/restore
6. Click on the `Restoration Plans` tab
7. Click a blue waterbody on the map
8. Verify the popup loads with a list of Restoration Plans
9. Click a surrounding waterbody on the map
10. Verify the normal waterbody popup is shown
11. Navigate to http://localhost:3000/community/070700030302/protect
12. Expand the `Protection Projects` accordion
13. Click a blue waterbody on the map
14. Verify the popup loads with a list of Protection Plans
    * This one will take longer as the Wisconsin plans have a over a thousand associated waters
15. Click a surrounding waterbody on the map
16. Verify the normal waterbody popup is shown

2024-06-07 19:42 UTC, maxdiebold-erg requested changes
Nice, this is much faster!

The only thing I noticed is that there's an extra `actions?` in two calls on the Waterbody Report page:

![image](https://github.com/Eastern-Research-Group/mywaterway/assets/104089016/7f259330-f006-4aa3-8dc3-680165026cf6)

This still works, it seems the browser is stripping off the extra, but if we want to remove it then I think two of the `parameter` definitions in `WaterbodyReport.js` should have just the parameters, not the tail of the path or the `?`.

2024-06-10 11:59 UTC, cschwinderg commented
Good catch! Should be fixed now.

2024-06-10 12:19 UTC, maxdiebold-erg commented
Thanks for fixing that!

2024-06-10 12:19 UTC, maxdiebold-erg approved these changes

2024-06-10 12:19 UTC, merged